PKGDIR ?= ../..
L4DIR  ?= /home/beleg/l4re/src/l4
O 	   ?= /home/beleg/l4re/obj/l4/arm64
TARGET = $(PKGNAME)_date.a $(PKGNAME)_date.p.a
SRC_C  = o_time.c
PC_FILENAME = $(PKGNAME)_date
CFLAGS += -I$(PKGDIR)/include/

#REQUIRES_LIBS =
#DEPENDS_LIBS = $(REQUIRES_LIBS)

include $(L4DIR)/mk/lib.mk


