PKGDIR ?= ..
L4DIR ?=/home/beleg/l4re/src/l4
TARGET  = bn evp core conf rand providers err threads selftest context provider exdata cryptlib aria modes cast bf objects lhash ctype
include $(L4DIR)/mk/subdir.mk
