PKGDIR ?= ..
L4DIR ?=/home/beleg/l4re/src/l4
TARGET  = bn evp core conf rand providers err threads selftest context provider exdata cryptlib aria modes cast bf objects lhash ctype x509 buffer fopen dsa sha dh rsa hmac ssl cmac rc2 async
include $(L4DIR)/mk/subdir.mk
